INSERT INTO ROOM(ID, NAME, FLOOR) VALUES(-10, 'Room1', 1);
INSERT INTO ROOM(ID, NAME, FLOOR) VALUES(-9, 'Room2', 1);

INSERT INTO LIGHT(LIGHT_ID, LEVEL, A, B, STATUS, ROOM_ID) VALUES (-1, 8, 50.0, 20.0, 'ON', -10);
INSERT INTO LIGHT(LIGHT_ID, LEVEL, A, B, STATUS, ROOM_ID) VALUES (-2, 0, 5.0, 2.0, 'OFF', -10);